export const courseList = [
  { course: "B.E (Automobile Engineering)", shortform: "Automobile" },
  { course: "B.E (Biomedical Engineering)", shortform: "Biomedical" },
  { course: "B.E (Civil Engineering)", shortform: "Civil" },
  {
    course: "B.E (Computer Science and Engineering (AI and ML))",
    shortform: "CSE(AI & ML)",
  },
  { course: "B.E (Computer Science and Engineering)", shortform: "CSE" },
  {
    course: "B.E (Electrical and Electronics Engineering)",
    shortform: "EEE",
  },
  {
    course: "B.E (Electronics and Communication Engineering)",
    shortform: "ECE",
  },
  {
    course: "B.E (Instrumentation and Control Engineering)",
    shortform: "Automobile",
  },
  { course: "B.E (Mechanical Engineering)", shortform: "Automobile" },
  { course: "B.E (Metallurgical Engineering)", shortform: "Automobile" },
  { course: "B.E (Production Engineering)", shortform: "Automobile" },
  { course: "B.E (Robotics and Automation)", shortform: "Automobile" },
  { course: "B.Tech (Bio Technology)", shortform: "Automobile" },
  { course: "B.Tech (Fashion Technology)", shortform: "Automobile" },
  { course: "B.Tech (Information Technology)", shortform: "Automobile" },
  { course: "B.Tech (Textile Technology)", shortform: "Automobile" },
  {
    course: "B.E (Electrical and Electronics Engineering) (Sandwich)",
    shortform: "Automobile",
  },
  {
    course: "B.E (Mechanical Engineering) (Sandwich)",
    shortform: "Automobile",
  },
  { course: "B.E (Production Engieering) (Sandwich)", shortform: "Automobile" },
  { course: "B.E (Robotics and Automation)", shortform: "Automobile" },
  { course: "M.E (Applied Electronics)", shortform: "Automobile" },
  { course: "M.E (Automative Engineering)", shortform: "Automobile" },
  { course: "M.E (Biometrics and Cybersecurity)", shortform: "Automobile" },
  { course: "M.E (Communication Systems)", shortform: "Automobile" },
  {
    course: "M.E (Computer Integrated Manufacturing)",
    shortform: "Automobile",
  },
  { course: "M.E (Computer Science and Engineering)", shortform: "Automobile" },
  { course: "M.E (Control Systems)", shortform: "Automobile" },
  { course: "M.E (Embedded & Real-Time-Systems)", shortform: "Automobile" },
  { course: "M.E (Energy Engineering)", shortform: "Automobile" },
  { course: "M.E (Engineering Design)", shortform: "Automobile" },
  { course: "M.E (Industrial Engineering)", shortform: "Automobile" },
  { course: "M.E (Industrial Metallurgy)", shortform: "Automobile" },
  { course: "M.E (Infrastructure Engineering)", shortform: "Automobile" },
  { course: "M.E (Manufacturing Engineering)", shortform: "Automobile" },
  { course: "M.E (Power Electronics and Drives)", shortform: "Automobile" },
  { course: "M.E (Structural Engineering)", shortform: "Automobile" },
  { course: "M.E (VLSI Design)", shortform: "Automobile" },
  { course: "M.Tech (Bio Technology)", shortform: "Automobile" },
  { course: "M.Tech (Information Technology)", shortform: "Automobile" },
  { course: "M.Tech (Nano Science and Technology)", shortform: "Automobile" },
  { course: "M.Tech (Textile Technology)", shortform: "Automobile" },
  { course: "Master of Computer Applications", shortform: "Automobile" },
  {
    course: "M.Sc (Fashion Design & Merchandising - 5 Years Integrated)",
    shortform: "Automobile",
  },
  { course: "M.Sc (Applied Mathematics)", shortform: "Automobile" },
  {
    course: "M.Sc (Software Systems - 5 Years Integrated)",
    shortform: "Automobile",
  },
  {
    course: "M.Sc (Theoretical Computer Scient - 5 Years Integrated)",
    shortform: "Automobile",
  },
  {
    course: "M.Sc (Data Science - 5 Years Integrated)",
    shortform: "Automobile",
  },
  {
    course: "M.Sc (Cyber Security - Integrated - 5 Years Integrated)",
    shortform: "Automobile",
  },
  {
    course: "BSc (Applied Science)",
    shortform: "Automobile",
  },
  { course: "BSc (Computer Systems and Design)", shortform: "Automobile" },
  { course: "MBA", shortform: "Automobile" },
  {
    course: "MBA (Waste Management & Social Entrepreneurship)",
    shortform: "Automobile",
  },
];
